list_of_cars = ['mazda', 'toyota', 'subaru']
# list of function in chapter 3.
    # value_name.title()
print(list_of_cars[0].title())
    # list_name.append('value_name')
print(list_of_cars.append('audi'))
print(list_of_cars)
    # listn_name.insert(position, 'value_name')
list_of_cars.insert(4, 'kamaz')
print(list_of_cars)
    # del list or value[index]
del list_of_cars[4]
print(list_of_cars)
    # list_name.pop()
list_of_cars.pop(0)
print(list_of_cars)
    # list_name.remove(value_name)
list_of_cars.remove('audi')
print(list_of_cars)
    # list_name.sort()
list_of_cars.sort()
print(list_of_cars)
    # list_name.sort(reverse=True)
list_of_cars.sort(reverse=True)
print(list_of_cars)
    # sorted(list_name)
print(sorted(list_of_cars))
    # list_name.revrse()
list_of_cars.reverse()
