# Generated by Django 3.2.7 on 2021-09-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Tuesday', 'Tuesday')], max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('quiche', 'Quiche'), ('toast', 'Toast')], max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_plans.planner')),
            ],
        ),
    ]
