# Generated by Django 3.2.7 on 2021-09-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(default='breakfast', max_length=100)),
                ('snack', models.CharField(default='snack', max_length=100)),
                ('lunch', models.CharField(default='lunch', max_length=100)),
                ('supper', models.CharField(default='supper', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='planner',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='planner',
            name='day',
        ),
        migrations.AddField(
            model_name='planner',
            name='day_of_the_week',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.DeleteModel(
            name='Breakfast',
        ),
        migrations.AddField(
            model_name='planner',
            name='meal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meal_plans.meal'),
        ),
    ]
