# Generated by Django 3.2.7 on 2021-09-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0002_auto_20210911_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planner',
            options={'verbose_name_plural': 'planner'},
        ),
    ]
