# Generated by Django 3.2.7 on 2021-09-12 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0004_auto_20210911_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOftheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='dayoftheweek',
            name='meals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_plans.mealplan'),
        ),
    ]
