# Generated by Django 3.2.7 on 2021-09-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='tagline',
        ),
    ]
