# Generated by Django 3.2.7 on 2021-09-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_rename_name_topping_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='topping',
            field=models.CharField(max_length=50),
        ),
    ]
